# -*- mode: ruby -*-
# vi: set ft=ruby :

REQUIRED_PLUGINS = %w( vagrant-proxyconf vagrant-hostmanager )
REQUIRED_PLUGINS.all? do |plugin|
  Vagrant.has_plugin?(plugin) || (
    puts "The #{plugin} plugin is required. Please install it with:"
    puts "$ vagrant plugin install #{plugin}"
    false
  )
end

# Print error information and exit:
#
# - Ref: [javiroman/TestBeds](https://github.com/javiroman/TestBeds)
# - Souce code: [vagrant/lib/vagrant/errors.rb at main · hashicorp/vagrant · GitHub](https://github.com/hashicorp/vagrant/blob/main/lib/vagrant/errors.rb)
#
#def fail_with_message(msg)
#    fail Vagrant::Errors::VagrantError.new, msg
#end
#
# - Usage:
### fail_with_message "This is an error"


# Print information:
#
# - Ref: [oracle/vagrant-projects](https://github.com/oracle/vagrant-projects)
# - Souce code: [vagrant/lib/vagrant/ui.rb at main · hashicorp/vagrant · GitHub](https://github.com/hashicorp/vagrant/blob/main/lib/vagrant/ui.rb)
#
#ui = Vagrant::UI::Prefixed.new(Vagrant::UI::Colored.new, "vagrant")
#
# - Usage:
### ui.info "This is an info"
### ui.warn "This is a warn"
### ui.error "This is an error"
### ui.success "This is a success"

# Variables to set:
#
servers = [
  {
    ## Vagrant Box's Name:
    :box_name => "bento/rockylinux-8",       # (in parallels Provider)
    # :box_name => "rockylinux/8",       # (in vmware_desktop Provider)
    ## VM's Name used by Vagrant:
    :vm_name => "k8s-1-28-master-01",
    ## VM's Hostname:
    :host_name => "k8s-1-28-master-01",
    ## VM's CPU count:
    :node_cpu => 2,
    ## VM's memory (MiB):
    :node_mem => 4096
  },
  {
    :box_name => "bento/rockylinux-8",
    :vm_name => "k8s-1-28-master-02",
    :host_name => "k8s-1-28-master-02",
    :node_cpu => 2,
    :node_mem => 4096
  },
  {
    :box_name => "bento/rockylinux-8",
    :vm_name => "k8s-1-28-master-03",
    :host_name => "k8s-1-28-master-03",
    :node_cpu => 2,
    :node_mem => 4096
  }
]

# Host Locale Environment Variables:
#
# Usually, host locale environment variables are passed to guest.
#
# - Ref: [Tips & Tricks - Vagrantfile | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/vagrantfile/tips)
#
# To override host locale environment variables:
ENV["LC_ALL"] = "en_US.UTF-8"
ENV["LC_CTYPE"] = "en_US.UTF-8"


# Vagrant Environment Variables:
#
# - Ref: [Environmental Variables | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/other/environmental-variables)

## VAGRANT_LOG:
## Set Vagrant Log Level
##
## - Ref: [Debugging and Troubleshooting | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/other/debugging)
## - Value:
##     - 'debug': loud
##     - 'info': normal
##     - 'warn': quiet
##     - 'error': very quiet
## - Default: "" (empty), Vagrant does not show any log messages
##
ENV['VAGRANT_LOG'] = 'error'

## VAGRANT_NO_PARALLEL:
## stop parallel operations
##
## - Default: "no", do not stop
## 
ENV['VAGRANT_NO_PARALLEL'] = 'no'


# Minimum Vagrant version:
#
# - Ref: [Minimum Vagrant Version - Vagrantfile | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/vagrantfile/vagrant_version)
# - Note: required by 'vagrant-parallels' plugin
#
Vagrant.require_version ">= 1.9.7"


# Vagrantfile API/syntax version. 
#
# - Note: Don't touch unless you know what you're doing!
#
VAGRANTFILE_API_VERSION = "2" if not defined? VAGRANTFILE_API_VERSION

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Settings for 'vagrant-proxyconf' plugin:
  #
  # - Ref: [tmatilai/vagrant-proxyconf](https://github.com/tmatilai/vagrant-proxyconf)
  # - Sample:
  ### if Vagrant.has_plugin?("vagrant-proxyconf")
  ###   config.proxy.http     = "http://<proxy-server>:<proxy-port>"
  ###   config.proxy.https    = "http://<proxy-server>:<proxy-port>"
  ###   config.proxy.no_proxy = "localhost,127.0.0.1"
  ###   config.proxy.enabled = { pear: false, yum: false, docker: false }
  ### end
  #
  #
  # Or :
  ### Disable plugin 'vagrant-proxyconf' completely:
  ###
  ### if Vagrant.has_plugin?("vagrant-proxyconf")
  ###   config.proxy.enabled = false
  ### end
  #
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.enabled  = { pear: false, npm: false }
  end
  
  # Settings for 'vagrant-hostmanager' plugin:
  #
  # - Ref: [devopsgroup-io/vagrant-hostmanager](https://github.com/devopsgroup-io/vagrant-hostmanager)
  #
  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    # config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
  end

  servers.each do |machine|
    # Name of VM:
    # used by Vagrant
    #
    # - Ref: [configuration - How to change Vagrant 'default' machine name? - Stack Overflow](https://stackoverflow.com/questions/17845637/how-to-change-vagrant-default-machine-name)
    # - Default: "default"
    # - Note: Do not change this after 'vagrant up' !
    config.vm.define machine[:vm_name] do |node|

      # Vagrant Box:
      #
      # - Ref: [Install and Specify a Box | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/tutorials/getting-started/getting-started-boxes)
      #
      node.vm.box = machine[:box_name]
      
      # Vagrant Box version:
      #
      # - Ref: [Box Versioning | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/boxes/versioning)
      # - Default: ">= 0" (latest)
      #
      node.vm.box_version = ">= 0"

      # URL of Vagrant Box to download:
      #node.vm.box_url = ""

      # Hostname in VM:
      # used by VM, '[vagrant@hotname]'
      #
      # - Default: "nil" (Vagrant will not manage the hostname)
      # - Note: To change this option after VM is created, execute 'vagrant reload' is required.
      #
      node.vm.hostname = machine[:host_name]

      # Replace Vagrant's default insecure SSH key:
      #
      # - Ref: [config.ssh - Vagrantfile | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/vagrantfile/ssh_settings)
      # - Vaule:
      #     - "true": Generate a new SSH keypair, and insert into the VM. This will replace Vagrant's default insecure key inside the VM.
      #               New key: ".vagrant/machines/#{HOST_NAME}/parallels/private_key"
      #     - "false": Do not replace. Still use Vagrant's default insecure key.
      #                Old key: "~/.vagrant.d/insecure_private_key"
      # - Default: "true"
      #
      #node.ssh.insert_key = false

      # Disable the default Vagrant synced folder "/vagrant". Comment to enable:
      #
      # - Ref: [Basic Usage - Synced Folders | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/synced-folders/basic_usage)
      #
      node.vm.synced_folder ".", "/vagrant", disabled: true

      # Synced Folders:
      #
      # - Ref: [Basic Usage - Synced Folders | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/synced-folders/basic_usage)
      #
      #node.vm.synced_folder "src/", "/srv/website"

      # VMware Desktop Provider:
      #
      # - Ref: [Configuration - VMware Provider | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/providers/vmware/configuration)
      #
      node.vm.provider "vmware_desktop" do |v, override|

        # Display name of VM:
        # used by VMware workstation / Fusion
        # formerly: "v.displayname"
        #
        v.vmx["displayName"] = machine[:vm_name]

        # Vagrant Box:
        #
        # - Ref: [Install and Specify a Box | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/tutorials/getting-started/getting-started-boxes)
        #
        override.vm.box = "rockylinux/8"

        # Vagrant Box version:
        #
        # - Ref: [Box Versioning | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/boxes/versioning)
        # - Default: ">= 0" (latest)
        #
        override.vm.box_version = ""

        # URL of Vagrant Box to download:
        # Rocky Linux Offical: "https://dl.rockylinux.org/pub/rocky/8/images/x86_64/Rocky-8-Vagrant-VMware.latest.x86_64.box"
        override.vm.box_url = "https://mirrors.aliyun.com/rockylinux/8/images/x86_64/Rocky-8-Vagrant-VMware.latest.x86_64.box"

        # Full Clone / Linked Clone:
        # 
        # - Value:
        #     - 'false': Full Clone. 
        #         - Pro: Full image copy. Totally independent from the box.
        #         - Con: Slower when 'vagrant up'. Use more disk space.
        #     - 'true': Linked Clone. 
        #         - Pro: Faster when 'vagrant up'. Use less disk space.
        #         - Con: The box deletion will make all its linked clones not working.
        # - Default: 'true' (Recommended)
        # - Note: Changes of this setting will take an effect only for newly created machines.
        #
        v.linked_clone = true

        # Launch guest with the GUI:
        #
        # - Default: false
        # - Note: Set to 'false' is not recommended. It will cause VMware Workstation/ Fusion can not get the new VM's infomation.
        #
        #v.gui = true

        # Time to pause after applying port forwarding configuration:
        # This allows guest time to acquire DHCP address if previous address is dropped when VMware network services are restarted.
        #
        # - Unit: seconds
        #
        v.port_forward_network_pause = 8

        # Allow list VMX settings:
        #
        v.allowlist_verified = true

        # VM memory size:
        #
        # - Unit: MiB
        #
        v.vmx["memsize"] = machine[:node_mem]

        # VM number of CPUs:
        #
        v.vmx["numvcpus"] = machine[:node_cpu]

        # VM number of CPU cores per socket:
        #
        # - Note: 'numvcpus' must be divisible by 'cpuid.coresPerSocket'
        #
        #v.vmx["cpuid.coresPerSocket"] = "1"

        # Enable nested virtualization:
        #
        v.vmx["vhv.enable"] = "false"

        # Use paravirtualized virtual hardware:
        #
        #v.vmx["ethernet0.virtualDev"] = "vmxnet3"

        # eth0's networking mode is always NAT. Change to other mode:
        #
        # - Ref: [Networking | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/networking#there-is-a-nat-available)
        # - Ref: [Vagrant Box - eth0 NAT · Issue #2093 · hashicorp/vagrant](https://github.com/hashicorp/vagrant/issues/2093)
        # - Default: "nat"
        # - Note: This may lead to inconsistent behavior.
        #
        # Host-Only mode:
        #v.vmx["ethernet0.connectiontype"] = "hostonly"
        # Bridged mode:
        #v.vmx["ethernet0.connectiontype"] = "bridged"

      end # of v


      # Parallels Desktop Provider:
      #
      # - Ref: [Configuration - Vagrant Parallels Provider Documentation](http://parallels.github.io/vagrant-parallels/docs/configuration.html)
      #
      node.vm.provider "parallels" do |prl|

        # Display name of VM:
        # used by Parallels Desktop
        # By default, Vagrant sets it to the name of the folder containing the Vagrantfile plus a timestamp of when the machine was created.
        # 
        # - Note: To change this option after VM is created, execute 'vagrant reload' is required.
        #
        prl.name = machine[:vm_name]

        # Full Clone / Linked Clone:
        # 
        # - Value:
        #     - 'false': Full Clone. 
        #         - Pro: Full image copy. Totally independent from the box.
        #         - Con: Slower when 'vagrant up'. Use more disk space.
        #     - 'true': Linked Clone. 
        #         - Pro: Faster when 'vagrant up'. Use less disk space.
        #         - Con: The box deletion will make all its linked clones not working.
        # - Default: 'true' (Recommended)
        # - Note: Changes of this setting will take an effect only for newly created machines.
        # - Requirements: vagrant-parallels > v2.0.0
        #
        prl.linked_clone = true

        # Parallels Tools Auto-Update:
        #
        # - Value:
        #     - 'false': Turn off Auto-Update
        #     - 'true': Turn on Auto-Update
        # - Default: 'false'
        #
        prl.update_guest_tools = false

        # VM memory size:
        #
        # - Unit: MiB
        #
        prl.memory = machine[:node_mem]

        # VM number of CPUs:
        #
        prl.cpus = machine[:node_cpu]

        # Customization with prlctl:
        # 'prl.customize' use 'prlctl' to modify the VM's settings.
        # 
        # - 'prl.customize' options:
        #     - 'prl.customize "post-import"': Default. executed only once, just after the VM is cloned from the base box
        #     - 'prl.customize "pre-boot"': executed prior to VM booting
        #     - 'prl.customize "post-boot"': executed after VM booting, before the communicator (ssh or winrm) confirms the connection
        #     - 'prl.customize "post-comm"': executed after VM booting, after the communicator (ssh or winrm) confirms the connection
        #
        # - Sample:
        ### prl.customize ["set", :id, "--device-set", "cdrom0", "--image", "/path/to/disk.iso", "--connect"]
        ### prl.customize "post-import", ["set", :id, "--nested-virt", "on"]

        # Launch guest with the GUI:
        #
        # - Ref: [Please enable `prl.gui = true` for parity with Virtualbox and VMware providers · Issue #355 · Parallels/vagrant-parallels](https://github.com/Parallels/vagrant-parallels/issues/355)
        #
        #prl.customize ["set", :id, "--startup-view", "window"]

        # Stop sharing printers:
        #
        prl.customize "pre-boot", ["set", :id, "--sync-host-printers", "off"]
        prl.customize "pre-boot", ["set", :id, "--sync-default-printer", "off"]

        # Automatically start on boot:
        #
        prl.customize ["set", :id, "--onboot", "yes"]

      end # of prl
    end # of node
  end # machine

  # VM OS Type:
  # Vagrant will auto-detect
  #
  # - Value:
  #     - ':linux'
  #     - ':windows'
  # - Default: ':linux'
  # - Note: Do not set this option when using VMware Workstation / Fusion. Or error may occur:
  #     "Vagrant attempted to execute the capability 'configure_networks'
  #     on the detect guest OS 'linux', but the guest doesn't
  #     support that capability. This capability is required for your
  #     configuration of Vagrant. Please either reconfigure Vagrant to
  #     avoid this capability or fix the issue by creating the capability."
  #
  # config.vm.guest = :linux

  # How long Vagrant will keep trying to connect to the VM before it assume something went wrong and times out:
  #
  # - Default: "300"
  # - Unit: second
  #
  config.vm.boot_timeout = 600

  # How to commumicate with the VM:
  #
  # - Vaule:
  #     - "winrm": for Windows VM
  #     - "ssh": for *nix VM
  # - Default: "ssh"
  #
  config.vm.communicator = "ssh"

  # Enable provisioning with a shell script:
  #
  # - Ref:[Shell Scripts - Provisioning | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/provisioning/shell)
  #
  config.vm.provision "shell" do |shell|
    shell.inline = <<-'SHELL_SCRIPT'
      echo " ====== Linux: Recording box generation date ====> "
      date > /etc/vagrant_box_build_date

      echo " ====== Linux: Set Timezone ====> "
      timedatectl set-timezone "Asia/Shanghai"

      echo " ====== DNF: Enable Extras REPO ====> "
      dnf config-manager --set-enabled extras powertools

      echo " ====== DNF: Config Rocky Linux 8 REPO mirror ====> "
      sed -e 's|^\(mirrorlist\s*=\s*\)|#\1|g' \
          -e 's|^#\s*\(baseurl\s*=\s*\)http://dl.rockylinux.org/\$contentdir|\1https://mirrors.aliyun.com/rockylinux|g' \
          -i.default \
          /etc/yum.repos.d/Rocky-AppStream.repo \
          /etc/yum.repos.d/Rocky-BaseOS.repo \
          /etc/yum.repos.d/Rocky-Extras.repo \
          /etc/yum.repos.d/Rocky-PowerTools.repo
      dnf --disablerepo=* --enablerepo=appstream,baseos,extras,powertools makecache

      # From:
      # - [Installing kubeadm | Kubernetes](https://v1-28.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#before-you-begin)
      echo " ====== Linux: Disable SWAP ====> "
      swapoff -a
      cp /etc/fstab /etc/fstab.original
      sed -ri '/\sswap\s/s/^#?/#/' /etc/fstab

      # From:
      # - [Container Runtimes | Kubernetes](https://v1-28.docs.kubernetes.io/docs/setup/production-environment/container-runtimes/#forwarding-ipv4-and-letting-iptables-see-bridged-traffic)
      echo " ====== DNF: Install container runtime containerd ====> "
      cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
      overlay
      br_netfilter
      EOF
      sudo modprobe overlay
      sudo modprobe br_netfilter
      # sysctl params required by setup, params persist across reboots
      cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
      EOF
      # Apply sysctl params without reboot
      sudo sysctl --system

      echo " ====== DNF: Install Docker REPO ====> "
      yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

      echo " ====== DNF: Config Docker REPO Mirror ====> "
      sed -e 's|^\(baseurl\s*=\s*\)https://download.docker.com|\1https://mirrors.tuna.tsinghua.edu.cn/docker-ce|g' \
          -i.default \
          /etc/yum.repos.d/docker-ce.repo

      # From:
      # - [Installing kubeadm | Kubernetes](https://v1-28.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-runtime)
      # - [containerd/docs/getting-started.md at main · containerd/containerd](https://github.com/containerd/containerd/blob/main/docs/getting-started.md)
      echo " ====== DNF: Install container runtime containerd ====> "
      yum -y install containerd.io # containerd & runc

      # From:
      # - [containerd/docs/getting-started.md at main · containerd/containerd](https://github.com/containerd/containerd/blob/main/docs/getting-started.md)
      echo " ====== DNF: Install CNI plugins ====> "
      yum -y install containernetworking-plugins
      
      echo " ====== DNF: Install Kubernetes REPO ====> "

      

      # Set SELinux in permissive mode (effectively disabling it)
      setenforce 0
      sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

      echo " ====== iTerm2: Shell Integration ====> "
      # [Shell Integration - Documentation - iTerm2 - macOS Terminal Replacement](https://iterm2.com/documentation-shell-integration.html)
      FILENAME="/etc/profile.d/iterm2.sh"
      sudo curl -SsL "https://ghp.ci/https://raw.githubusercontent.com/gnachman/iTerm2-shell-integration/main/shell_integration/bash" -o "${FILENAME}"
      sudo chmod +x "${FILENAME}"

    SHELL_SCRIPT
    shell.reboot = false
    shell.args   = ""
  end # of shell


  # Empty provisioning for re-triggering Vagrant Plugin "vagrant-proxyconf":
  #
  config.vm.provision "proxyconf", run: "never", type: "shell" do |shell|
    shell.inline = ""
    shell.reboot = false
    shell.args   = ""
  end # of shell

  # Enable provisioning with Ansible Playbook:
  #
  # - Ref: [Ansible - Provisioning | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/provisioning/ansible)
  # - Ref: [Multiple provision scripts (with option to manually invoke them) · Issue #9015 · hashicorp/vagrant](https://github.com/hashicorp/vagrant/issues/9015)
  #
  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook           = "playbook.yml"
  #   ansible.compatibility_mode = "2.0"
  # end

  # Automatic box update checking:
  #
  # - Value:
  #     - 'false': Turn off. Boxes will only be checked for updates when the user runs `vagrant box outdated`. This is not recommended.
  #     - 'true': Turn on. If an update is found, Vagrant will tell the user.
  # - Default: 'true'
  # - Note: Updates will only be checked for boxes that properly support updates (boxes from HashiCorp's Vagrant Cloud or some other versioned box).
  #
  config.vm.box_check_update = true

  # Forwarded ports:
  # 
  # - Ref: [Forwarded Ports - Networking | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/networking/forwarded_ports)
  # - Ref: [Public Networks - Networking - Vagrant Parallels Provider Documentation](http://parallels.github.io/vagrant-parallels/docs/networking/public_network.html)
  #
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  #
  # - Note: This will enable public access to the opened port
  #
  #HOST_PORT = 8080
  #GUEST_PORT = 8080
  #config.vm.network "forwarded_port", guest: GUEST_PORT, host: HOST_PORT, protocol: "tcp"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  #config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Private Networks:
  # Create a new Host-Only Network adapter.
  #
  # - Ref: [Private Networks - Networking | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/networking/private_network)
  # - Ref: [Private Networks - Networking - Vagrant Parallels Provider Documentation](http://parallels.github.io/vagrant-parallels/docs/networking/private_network.html)
  #
  # Create a private network, with a specific IP:
  #config.vm.network "private_network", ip: "192.168.33.10"
  #
  # Create a private newtwork, get IP from DHCP:
  #config.vm.network "private_network", type: "dhcp"

  # Public Networks:
  # Create a new Bridged Network adapter. Bridged networks make the machine appear as another physical device on your network.
  #
  # - Ref: [Public Networks - Networking | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/networking/public_network)
  # - Ref: [Public Networks - Networking - Vagrant Parallels Provider Documentation](http://parallels.github.io/vagrant-parallels/docs/networking/public_network.html)
  #
  # Create a public network:
  #config.vm.network "public_network"

  # SSH private key to login to VM:
  # If you're working with a team or company or with a custom box and you want more secure SSH, you should create your own keypair.
  #
  # - Ref: [vagrant/keys at main · hashicorp/vagrant](https://github.com/hashicorp/vagrant/tree/main/keys)
  #
  #config.ssh.private_key_path = ""

  # SSH password to login to VM:
  #
  # - Ref: ["vagrant" User - Creating a Base Box | Vagrant | HashiCorp Developer](https://developer.hashicorp.com/vagrant/docs/boxes/base#vagrant-user)
  # - Note: key-based authentication is recommended
  #
  #config.ssh.password = "vagrant"

  # SSH Server port of VM:
  #
  # - Default: 22
  #
  config.ssh.guest_port = 22

end # of config
