ungrouped:
  hosts:
    single-rocky8-ansible-hosts:
      # ansible_host: <guest IP>
      ansible_connection: paramiko
      ansible_port: 22
      ansible_user: vagrant
      ansible_password: vagrant
      # ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
      # ansible_ssh_private_key_file: ".vagrant/machines/{{ inventory_hostname }}/parallels/private_key"
      # ansible_ssh_common_args: '-o IdentitiesOnly=yes'
